from .TranslationNode import NODE_CLASS_MAPPINGS as TRANSLATION_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TRANSLATION_NODE_DISPLAY_NAME_MAPPINGS
from .DownloadModelsNode import NODE_CLASS_MAPPINGS as MIRROR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MIRROR_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**TRANSLATION_NODE_CLASS_MAPPINGS, **MIRROR_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TRANSLATION_NODE_DISPLAY_NAME_MAPPINGS, **MIRROR_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

WEB_DIRECTORY = "./web"  # 定义Web目录路径